# Generated by Django 3.1.4 on 2021-01-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='song_if',
            new_name='song_id',
        ),
    ]
